input {
  file {
    path => "/var/log/modsec/audit.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => "json"
  }
}

filter {
  mutate {
    copy => { "[transaction][client_ip]" => "client_ip" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "waf-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}