version: '3'

services:
  web_app:
    image: php:8.0-apache
    volumes:
      - ./source_code:/var/www/html/
    restart: always

  waf:
    image: owasp/modsecurity-crs:3.3.2-nginx
    ports:
      - "80:80"
    environment:
      - BACKEND=http://web_app:80
      - PARANOIA=1
      - MODSEC_AUDIT_ENGINE=On
      - MODSEC_AUDIT_LOG=/var/log/modsec/audit.log
      - MODSEC_AUDIT_LOG_FORMAT=JSON
    volumes:
      - ./waf:/var/log/modsec/
      - blacklist_vol:/etc/nginx/conf.d/
    depends_on:
      - web_app

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.license.self_generated.type=basic
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=X-Requested-With,Content-Type,Content-Length,Authorization
      - http.cors.allow-methods=OPTIONS,HEAD,GET,POST,PUT,DELETE
    ports:
      - "9201:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.0
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./waf:/var/log/modsec/
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  auto_blocker:
    build:
      context: ./auto_blocker
      dockerfile: Dockerfile
    volumes:
      - blacklist_vol:/etc/nginx/conf.d/
      - /var/run/docker.sock:/var/run/docker.sock  
    depends_on:
      - elasticsearch
      - waf
    restart: always

volumes:          
  es_data:
  blacklist_vol: